version: "3.8"
services:
  carapi:
    build:
      context: .
      dockerfile: docker/carapi/Dockerfile
    depends_on:
      - carweb
      - database
    ports:
      - 8081:8081
    expose:
      - 8080
    volumes:
      - .:/app
      - modules_data:/app/carweb/node_modules
    working_dir: /app
    command: ./gradlew bootRun
    tty: true
  carweb:
    build:
      context: .
      dockerfile: docker/carweb/Dockerfile
    volumes:
      - .:/app
      - modules_data:/app/carweb/node_modules
    ports:
      - 8080:8080
    working_dir: /app/carweb
    command: npm run serve
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: cars_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - ./docker/database/config:/etc/mysql/conf.d
      - mysql_db:/var/lib/mysql
    cap_add:
      - SYS_NICE
volumes:
  modules_data:
  mysql_db:
    driver: local