spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://database/cars_db"
    username: "user"
    password: "password"
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
server:
  port: 8081